media:
  input: static/img
  output: /img
content:
  - name: blog
    label: Blog
    path: content/blog
    type: collection
    format: toml-frontmatter
    exclude: ["_index.md"]
    filename: "{year}-{month}-{day}-{primary}.md"
    fields:
      - name: title
        type: string
    view: 
      fields: [ title ]
      sort: [ title ]
      primary: title
      default:
        search: ''
        sort: title
        order: desc