name: deploy
env:
  ZOLA_VERSION: 0.16.0
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tags:
        description: 'Description tag.'
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Download and Run Zola
        run: |
          wget "https://github.com/getzola/zola/releases/download/v$ZOLA_VERSION/zola-v$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz" -O zola.tar.gz
          tar -xf zola.tar.gz
          ./zola build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          single-commit: true
          git-config-email: <>
          branch: gh-pages 
          folder: public
